feat(RELEASE-1675): auto generate README.md files for tasks/pipelines
Add readme_generator.sh, which generates README.md files
for tasks and pipelines, as well as a check_readme.sh script and
workflow to check that the README.md files in each task and pipeline
match the output of readme-generator.sh.

Also updated all README.md files using this script.

Signed-off-by: Paul Fitzgerald <pafitzge@redhat.com>

diff --git a/tasks/internal/pulp-push-disk-images/pulp-push-disk-images.yaml b/tasks/internal/pulp-push-disk-images/pulp-push-disk-images.yaml
--- a/tasks/internal/pulp-push-disk-images/pulp-push-disk-images.yaml
+++ b/tasks/internal/pulp-push-disk-images/pulp-push-disk-images.yaml
@@ -7,8 +7,8 @@ metadata:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
 spec:
-  description: >-
-    Tekton task to push disk images with pulp
+  description: |-
+    Tekton task to push disk images with Pulp
   params:
     - name: snapshot_json
       type: string
@@ -110,181 +110,4 @@ spec:
             secretKeyRef:
               name: $(params.cgwSecret)
               key: token
-      script: |
-        #!/usr/bin/env bash
-        set -ex
-
-        STDERR_FILE=/tmp/stderr.txt
-
-        exitfunc() {
-            local err=$1
-            local line=$2
-            local command="$3"
-            if [ "$err" -eq 0 ] ; then
-                echo -n "Success" > "$(results.result.path)"
-            else
-                echo "$0: ERROR '$command' failed at line $line - exited with status $err" \
-                  > "$(results.result.path)"
-                if [ -f "$STDERR_FILE" ] ; then
-                    tail -n 20 "$STDERR_FILE" >> "$(results.result.path)"
-                fi
-            fi
-            exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call
-        }
-        # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
-        trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT
-
-        # Setup required variables
-        export EXODUS_GW_CERT=/tmp/exodus.crt
-        export EXODUS_GW_KEY=/tmp/exodus.key
-        export PULP_CERT_FILE=/tmp/pulp.crt
-        export PULP_KEY_FILE=/tmp/pulp.key
-        export UDCACHE_CERT=/tmp/udc.crt
-        export UDCACHE_KEY=/tmp/udc.key
-        EXODUS_GW_ENV=$(params.exodusGwEnv)
-        export EXODUS_GW_ENV
-        export EXODUS_GW_URL="$EXODUS_URL"
-        export EXODUS_PULP_HOOK_ENABLED=True
-        export EXODUS_GW_TIMEOUT=7200
-        mkdir -p ~/.docker
-
-        set +x
-        echo "$EXODUS_CERT" > "$EXODUS_GW_CERT"
-        echo "$EXODUS_KEY" > "$EXODUS_GW_KEY"
-        echo "$PULP_CERT" > "$PULP_CERT_FILE"
-        echo "$PULP_KEY" > "$PULP_KEY_FILE"
-        echo "$UDC_CERT" > "$UDCACHE_CERT"
-        echo "$UDC_KEY" > "$UDCACHE_KEY"
-        # Quotes are added to the secret so it applies in k8s nicely. But now we have to remove them
-        echo "$DOCKER_CONFIG_JSON" | sed -r 's/(^|\})[^{}]+(\{|$)/\1\2/g' > ~/.docker/config.json
-        set -x
-
-        DISK_IMAGE_DIR="$(mktemp -d)"
-        export DISK_IMAGE_DIR
-
-        process_component() { # Expected argument is [component json]
-            COMPONENT=$1
-            PULLSPEC=$(jq -er '.containerImage' <<< "${COMPONENT}")
-            DESTINATION="${DISK_IMAGE_DIR}/$(jq -er '.staged.destination' <<< "${COMPONENT}")/FILES" \
-              || (echo "Missing staged.destination value for component. This should be an existing pulp repo. \
-                  Failing" && exit 1)
-            mkdir -p "${DESTINATION}"
-            DOWNLOAD_DIR=$(mktemp -d)
-            cd "$DOWNLOAD_DIR"
-            # oras has very limited support for selecting the right auth entry,
-            # so create a custom auth file with just one entry
-            AUTH_FILE=$(mktemp)
-            select-oci-auth "${PULLSPEC}" > "$AUTH_FILE"
-            oras pull --registry-config "$AUTH_FILE" "$PULLSPEC"
-            NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< "${COMPONENT}")
-            for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
-                FILE=$(jq -c --arg i "$i" '.staged.files[$i|tonumber]' <<< "$COMPONENT")
-                SOURCE=$(jq -er '.source' <<< "$FILE")
-                FILENAME=$(jq -er '.filename' <<< "$FILE")
-                # The .qcow2 images are not zipped
-                if [ -f "${SOURCE}.gz" ] ; then
-                    gzip -d "${SOURCE}.gz"
-                fi
-                DESTINATION_FILE="${DESTINATION}/${FILENAME}"
-                # Albeit a rare one, this is a race condition since this is run in parallel.
-                # The race condition is if two files have the same $DESTINATION_FILE and both
-                # if checks are run before either mv is run a few lines below.
-                if [ -f "${DESTINATION_FILE}" ] ; then
-                    echo -n "Multiple files use the same destination value: $DESTINATION" >&2
-                    echo " and filename value: $FILENAME. Failing..." >&2
-                    exit 1
-                fi
-                mv "$SOURCE" "${DESTINATION_FILE}" || echo "didn't find mapped file: ${SOURCE}"
-            done
-
-        }
-
-        process_component_for_developer_portal() { # Expected argument are [component json], [content_directory]
-          COMPONENT=$1
-
-          productName="$(jq -er '.contentGateway.productName' <<< "${COMPONENT}")" \
-            || (echo "Missing contentGateway.productName value for component. This should be an existing product \
-                  in the Developer Portal. Failing" && exit 1)
-
-          productCode="$(jq -er '.contentGateway.productCode' <<< "${COMPONENT}")" \
-            || (echo "Missing contentGateway.productCode value for component. This should be an existing product \
-                  in the Developer Portal. Failing" && exit 1)
-
-          productVersionName="$(jq -er '.contentGateway.productVersionName' <<< "${COMPONENT}")" \
-            || (echo "Missing contentGateway.productVersionName value for component. This should be an existing \
-                  product in the Developer Portal. Failing" && exit 1)
-
-          filePrefix="$(jq -er '.contentGateway.filePrefix' <<< "${COMPONENT}")" \
-            || (echo "Missing contentGateway.filePrefix value for component. This should be the prefix for files to \
-                  upload to the Developer Portal. Failing" && exit 1)
-
-          developer_portal_wrapper --debug --product-name "${productName}" \
-            --product-code "${productCode}" \
-            --product-version-name "${productVersionName}" \
-            --cgw-hostname "$(params.cgwHostname)" \
-            --content-directory "$2" \
-            --file-prefix "${filePrefix}"
-
-        }
-
-        RUNNING_JOBS="\j" # Bash parameter for number of jobs currently running
-        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
-
-        # use the 1st component's version
-        VERSION=$(jq -cr '.components[0].staged.version // ""' <<< "$SNAPSHOT_JSON")
-        if [ "${VERSION}" == "" ] ; then
-          echo "Error: version not specified in .components[0].staged.version. Needed to publish to customer portal"
-          exit 1
-        fi
-
-        # Process each component in parallel
-        for ((i = 0; i < NUM_COMPONENTS; i++)) ; do
-            COMPONENT=$(jq -c --arg i "$i" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
-            # Limit batch size to concurrent limit
-            while (( ${RUNNING_JOBS@P} >= $(params.concurrentLimit) )); do
-                wait -n
-            done
-            process_component "$COMPONENT" 2> "$STDERR_FILE" &
-        done
-
-        # Wait for remaining processes to finish
-        while (( ${RUNNING_JOBS@P} > 0 )); do
-            wait -n
-        done
-
-        # Change to the subdir with the images
-        cd "${DISK_IMAGE_DIR}"
-
-        STAGED_JSON='{"header":{"version": "0.2"},"payload":{"files":[]}}'
-
-        # Add the files to the payload
-        # shell check wants us to find ./* but that adds `./` to the paths which breaks the script
-        # shellcheck disable=SC2035
-        while IFS= read -r -d '' file ; do
-            STAGED_JSON=$(jq --arg filename "$(basename "$file")" --arg path "$file" \
-              --arg version "$VERSION" \
-              '.payload.files[.payload.files | length] = 
-              {"filename": $filename, "relative_path": $path, "version": $version}' <<< "$STAGED_JSON")
-        done < <(find * -type f -print0)
-
-        echo "$STAGED_JSON" | yq -P -I 4 > staged.yaml
-
-        pulp_push_wrapper --debug --source "${DISK_IMAGE_DIR}" --pulp-url "$PULP_URL" \
-          --pulp-cert $PULP_CERT_FILE --pulp-key $PULP_KEY_FILE --udcache-url "$UDC_URL" \
-          2> "$STDERR_FILE"
-
-        relative_paths=$(echo "$STAGED_JSON" | jq -erc .payload.files[].relative_path)
-        component_destinations=()
-        for path in $relative_paths:
-        do
-          parent_dir=$(dirname "$path")
-          component_destinations+=("${DISK_IMAGE_DIR}/$parent_dir")
-        done
-
-        ## Process Files for Developer Portal / CGW
-        ##
-        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
-        for ((i = 0; i < NUM_COMPONENTS; i++)) ; do
-            COMPONENT=$(jq -c --arg i "$i" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
-            process_component_for_developer_portal "$COMPONENT" "${component_destinations[$i]}"  2> "$STDERR_FILE"
-        done
+      script: "#!/usr/bin/env bash\nset -ex\n\nSTDERR_FILE=/tmp/stderr.txt\n\nexitfunc() {\n    local err=$1\n    local line=$2\n    local command=\"$3\"\n    if [ \"$err\" -eq 0 ] ; then\n        echo -n \"Success\" > \"$(results.result.path)\"\n    else\n        echo \"$0: ERROR '$command' failed at line $line - exited with status $err\" \\\n          > \"$(results.result.path)\"\n        if [ -f \"$STDERR_FILE\" ] ; then\n            tail -n 20 \"$STDERR_FILE\" >> \"$(results.result.path)\"\n        fi\n    fi\n    exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call\n}\n# due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code\ntrap 'exitfunc $? $LINENO \"$BASH_COMMAND\"' EXIT\n\n# Setup required variables\nexport EXODUS_GW_CERT=/tmp/exodus.crt\nexport EXODUS_GW_KEY=/tmp/exodus.key\nexport PULP_CERT_FILE=/tmp/pulp.crt\nexport PULP_KEY_FILE=/tmp/pulp.key\nexport UDCACHE_CERT=/tmp/udc.crt\nexport UDCACHE_KEY=/tmp/udc.key\nEXODUS_GW_ENV=$(params.exodusGwEnv)\nexport EXODUS_GW_ENV\nexport EXODUS_GW_URL=\"$EXODUS_URL\"\nexport EXODUS_PULP_HOOK_ENABLED=True\nexport EXODUS_GW_TIMEOUT=7200\nmkdir -p ~/.docker\n\nset +x\necho \"$EXODUS_CERT\" > \"$EXODUS_GW_CERT\"\necho \"$EXODUS_KEY\" > \"$EXODUS_GW_KEY\"\necho \"$PULP_CERT\" > \"$PULP_CERT_FILE\"\necho \"$PULP_KEY\" > \"$PULP_KEY_FILE\"\necho \"$UDC_CERT\" > \"$UDCACHE_CERT\"\necho \"$UDC_KEY\" > \"$UDCACHE_KEY\"\n# Quotes are added to the secret so it applies in k8s nicely. But now we have to remove them\necho \"$DOCKER_CONFIG_JSON\" | sed -r 's/(^|\\})[^{}]+(\\{|$)/\\1\\2/g' > ~/.docker/config.json\nset -x\n\nDISK_IMAGE_DIR=\"$(mktemp -d)\"\nexport DISK_IMAGE_DIR\n\nprocess_component() { # Expected argument is [component json]\n    COMPONENT=$1\n    PULLSPEC=$(jq -er '.containerImage' <<< \"${COMPONENT}\")\n    DESTINATION=\"${DISK_IMAGE_DIR}/$(jq -er '.staged.destination' <<< \"${COMPONENT}\")/FILES\" \\\n      || (echo \"Missing staged.destination value for component. This should be an existing pulp repo. \\\n          Failing\" && exit 1)\n    mkdir -p \"${DESTINATION}\"\n    DOWNLOAD_DIR=$(mktemp -d)\n    cd \"$DOWNLOAD_DIR\"\n    # oras has very limited support for selecting the right auth entry,\n    # so create a custom auth file with just one entry\n    AUTH_FILE=$(mktemp)\n    select-oci-auth \"${PULLSPEC}\" > \"$AUTH_FILE\"\n    oras pull --registry-config \"$AUTH_FILE\" \"$PULLSPEC\"\n    NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< \"${COMPONENT}\")\n    for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do\n        FILE=$(jq -c --arg i \"$i\" '.staged.files[$i|tonumber]' <<< \"$COMPONENT\")\n        SOURCE=$(jq -er '.source' <<< \"$FILE\")\n        FILENAME=$(jq -er '.filename' <<< \"$FILE\")\n        # The .qcow2 images are not zipped\n        if [ -f \"${SOURCE}.gz\" ] ; then\n            gzip -d \"${SOURCE}.gz\"\n        fi\n        DESTINATION_FILE=\"${DESTINATION}/${FILENAME}\"\n        # Albeit a rare one, this is a race condition since this is run in parallel.\n        # The race condition is if two files have the same $DESTINATION_FILE and both\n        # if checks are run before either mv is run a few lines below.\n        if [ -f \"${DESTINATION_FILE}\" ] ; then\n            echo -n \"Multiple files use the same destination value: $DESTINATION\" >&2\n            echo \" and filename value: $FILENAME. Failing...\" >&2\n            exit 1\n        fi\n        mv \"$SOURCE\" \"${DESTINATION_FILE}\" || echo \"didn't find mapped file: ${SOURCE}\"\n    done\n\n}\n\nprocess_component_for_developer_portal() { # Expected argument are [component json], [content_directory]\n  COMPONENT=$1\n\n  productName=\"$(jq -er '.contentGateway.productName' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productName value for component. This should be an existing product \\\n          in the Developer Portal. Failing\" && exit 1)\n\n  productCode=\"$(jq -er '.contentGateway.productCode' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productCode value for component. This should be an existing product \\\n          in the Developer Portal. Failing\" && exit 1)\n\n  productVersionName=\"$(jq -er '.contentGateway.productVersionName' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productVersionName value for component. This should be an existing \\\n          product in the Developer Portal. Failing\" && exit 1)\n\n  filePrefix=\"$(jq -er '.contentGateway.filePrefix' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.filePrefix value for component. This should be the prefix for files to \\\n          upload to the Developer Portal. Failing\" && exit 1)\n\n  developer_portal_wrapper --debug --product-name \"${productName}\" \\\n    --product-code \"${productCode}\" \\\n    --product-version-name \"${productVersionName}\" \\\n    --cgw-hostname \"$(params.cgwHostname)\" \\\n    --content-directory \"$2\" \\\n    --file-prefix \"${filePrefix}\"\n\n}\n\nRUNNING_JOBS=\"\\j\" # Bash parameter for number of jobs currently running\nNUM_COMPONENTS=$(jq '.components | length' <<< \"$SNAPSHOT_JSON\")\n\n# use the 1st component's version\nVERSION=$(jq -cr '.components[0].staged.version // \"\"' <<< \"$SNAPSHOT_JSON\")\nif [ \"${VERSION}\" == \"\" ] ; then\n  echo \"Error: version not specified in .components[0].staged.version. Needed to publish to customer portal\"\n  exit 1\nfi\n\n# Process each component in parallel\nfor ((i = 0; i < NUM_COMPONENTS; i++)) ; do\n    COMPONENT=$(jq -c --arg i \"$i\" '.components[$i|tonumber]' <<< \"$SNAPSHOT_JSON\")\n    # Limit batch size to concurrent limit\n    while (( ${RUNNING_JOBS@P} >= $(params.concurrentLimit) )); do\n        wait -n\n    done\n    process_component \"$COMPONENT\" 2> \"$STDERR_FILE\" &\ndone\n\n# Wait for remaining processes to finish\nwhile (( ${RUNNING_JOBS@P} > 0 )); do\n    wait -n\ndone\n\n# Change to the subdir with the images\ncd \"${DISK_IMAGE_DIR}\"\n\nSTAGED_JSON='{\"header\":{\"version\": \"0.2\"},\"payload\":{\"files\":[]}}'\n\n# Add the files to the payload\n# shell check wants us to find ./* but that adds `./` to the paths which breaks the script\n# shellcheck disable=SC2035\nwhile IFS= read -r -d '' file ; do\n    STAGED_JSON=$(jq --arg filename \"$(basename \"$file\")\" --arg path \"$file\" \\\n      --arg version \"$VERSION\" \\\n      '.payload.files[.payload.files | length] = \n      {\"filename\": $filename, \"relative_path\": $path, \"version\": $version}' <<< \"$STAGED_JSON\")\ndone < <(find * -type f -print0)\n\necho \"$STAGED_JSON\" | yq -P -I 4 > staged.yaml\n\npulp_push_wrapper --debug --source \"${DISK_IMAGE_DIR}\" --pulp-url \"$PULP_URL\" \\\n  --pulp-cert $PULP_CERT_FILE --pulp-key $PULP_KEY_FILE --udcache-url \"$UDC_URL\" \\\n  2> \"$STDERR_FILE\"\n\nrelative_paths=$(echo \"$STAGED_JSON\" | jq -erc .payload.files[].relative_path)\ncomponent_destinations=()\nfor path in $relative_paths:\ndo\n  parent_dir=$(dirname \"$path\")\n  component_destinations+=(\"${DISK_IMAGE_DIR}/$parent_dir\")\ndone\n\n## Process Files for Developer Portal / CGW\n##\nNUM_COMPONENTS=$(jq '.components | length' <<< \"$SNAPSHOT_JSON\")\nfor ((i = 0; i < NUM_COMPONENTS; i++)) ; do\n    COMPONENT=$(jq -c --arg i \"$i\" '.components[$i|tonumber]' <<< \"$SNAPSHOT_JSON\")\n    process_component_for_developer_portal \"$COMPONENT\" \"${component_destinations[$i]}\"  2> \"$STDERR_FILE\"\ndone\n"
