fix linting

diff --git a/tasks/managed/verify-access-to-resources/verify-access-to-resources.yaml b/tasks/managed/verify-access-to-resources/verify-access-to-resources.yaml
--- a/tasks/managed/verify-access-to-resources/verify-access-to-resources.yaml
+++ b/tasks/managed/verify-access-to-resources/verify-access-to-resources.yaml
@@ -7,8 +7,11 @@ metadata:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
 spec:
-  description: >-
-    Tekton task to verify access to required resources & check if internal requests can be created.
+  description: |-
+    This Tekton task is used to verify access to various resources in the pipelines. It ensures that the necessary 
+    resources, such as the release, release plan, release plan admission, release service config and snapshot, are
+    available and accessible. Additionally, it checks if internal requests can be created if 
+    `requireInternalServices` is set to `true`.
   params:
     - name: release
       description: Namespace/name of the Release
@@ -39,54 +42,54 @@ spec:
           memory: 100Mi
           cpu: 10m
       script: |
-          #!/usr/bin/env bash
+        #!/usr/bin/env bash
 
-          ORIGIN_NAMESPACE="$(cut -f1 -d/ <<< "$(params.release)")"
-          TARGET_NAMESPACE="$(cut -f1 -d/ <<< "$(params.releasePlanAdmission)")"
-          RSC_NAMESPACE="$(cut -f1 -d/ <<< "$(params.releaseServiceConfig)")"
+        ORIGIN_NAMESPACE="$(cut -f1 -d/ <<< "$(params.release)")"
+        TARGET_NAMESPACE="$(cut -f1 -d/ <<< "$(params.releasePlanAdmission)")"
+        RSC_NAMESPACE="$(cut -f1 -d/ <<< "$(params.releaseServiceConfig)")"
 
-          RELEASE_NAME="$(cut -f2 -d/ <<< "$(params.release)")"
-          RELEASEPLAN_NAME="$(cut -f2 -d/ <<< "$(params.releasePlan)")"
-          RELEASEPLANADMISSION_NAME="$(cut -f2 -d/ <<< "$(params.releasePlanAdmission)")"
-          RELEASESERVICECONFIG_NAME="$(cut -f2 -d/ <<< "$(params.releaseServiceConfig)")"
-          SNAPSHOT_NAME="$(cut -f2 -d/ <<< "$(params.snapshot)")"
+        RELEASE_NAME="$(cut -f2 -d/ <<< "$(params.release)")"
+        RELEASEPLAN_NAME="$(cut -f2 -d/ <<< "$(params.releasePlan)")"
+        RELEASEPLANADMISSION_NAME="$(cut -f2 -d/ <<< "$(params.releasePlanAdmission)")"
+        RELEASESERVICECONFIG_NAME="$(cut -f2 -d/ <<< "$(params.releaseServiceConfig)")"
+        SNAPSHOT_NAME="$(cut -f2 -d/ <<< "$(params.snapshot)")"
 
-          CAN_I_READ_RELEASES="$(kubectl auth can-i get release/"${RELEASE_NAME}" -n "${ORIGIN_NAMESPACE}")"
-          CAN_I_READ_RELEASEPLANS="$(kubectl auth can-i get releaseplan/"${RELEASEPLAN_NAME}"\
-              -n "${ORIGIN_NAMESPACE}")"
-          CAN_I_READ_RELEASEPLANADMISSIONS="$(kubectl auth can-i get\
-              releaseplanadmission/"${RELEASEPLANADMISSION_NAME}" -n "${TARGET_NAMESPACE}")"
-          CAN_I_READ_RELEASESERVICECONFIG="$(kubectl auth can-i get\
-              releaseserviceconfig/"${RELEASESERVICECONFIG_NAME}" -n "${RSC_NAMESPACE}")"
-          CAN_I_READ_SNAPSHOTS="$(kubectl auth can-i get snapshot/"${SNAPSHOT_NAME}" -n "${ORIGIN_NAMESPACE}")"
+        CAN_I_READ_RELEASES="$(kubectl auth can-i get release/"${RELEASE_NAME}" -n "${ORIGIN_NAMESPACE}")"
+        CAN_I_READ_RELEASEPLANS="$(kubectl auth can-i get releaseplan/"${RELEASEPLAN_NAME}"\
+            -n "${ORIGIN_NAMESPACE}")"
+        CAN_I_READ_RELEASEPLANADMISSIONS="$(kubectl auth can-i get\
+            releaseplanadmission/"${RELEASEPLANADMISSION_NAME}" -n "${TARGET_NAMESPACE}")"
+        CAN_I_READ_RELEASESERVICECONFIG="$(kubectl auth can-i get\
+            releaseserviceconfig/"${RELEASESERVICECONFIG_NAME}" -n "${RSC_NAMESPACE}")"
+        CAN_I_READ_SNAPSHOTS="$(kubectl auth can-i get snapshot/"${SNAPSHOT_NAME}" -n "${ORIGIN_NAMESPACE}")"
 
-          if [ "$(params.requireInternalServices)" = "true" ]; then
-            CAN_I_CREATE_INTERNALREQUESTS="$(kubectl auth can-i create internalrequest -n "${TARGET_NAMESPACE}")"
-          else
-            CAN_I_CREATE_INTERNALREQUESTS="skipped"
-          fi
+        if [ "$(params.requireInternalServices)" = "true" ]; then
+          CAN_I_CREATE_INTERNALREQUESTS="$(kubectl auth can-i create internalrequest -n "${TARGET_NAMESPACE}")"
+        else
+          CAN_I_CREATE_INTERNALREQUESTS="skipped"
+        fi
 
+        echo ""
+        echo "CAN_I_READ_RELEASES? ${CAN_I_READ_RELEASES}"
+        echo "CAN_I_READ_RELEASEPLANS? ${CAN_I_READ_RELEASEPLANS}"
+        echo "CAN_I_READ_RELEASEPLANADMISSIONS? ${CAN_I_READ_RELEASEPLANADMISSIONS}"
+        echo "CAN_I_READ_RELEASESERVICECONFIG? ${CAN_I_READ_RELEASESERVICECONFIG}"
+        echo "CAN_I_READ_SNAPSHOTS? ${CAN_I_READ_SNAPSHOTS}"
+        echo ""
+        echo "CAN_I_CREATE_INTERNALREQUESTS? ${CAN_I_CREATE_INTERNALREQUESTS}"
+        echo ""
+
+        if [ "${CAN_I_READ_RELEASES}" = "no" ] ||\
+            [ "${CAN_I_READ_RELEASEPLANS}" = "no" ] ||\
+            [ "${CAN_I_READ_RELEASEPLANADMISSIONS}" = "no" ] ||\
+            [ "${CAN_I_READ_RELEASESERVICECONFIG}" = "no" ] ||\
+            [ "${CAN_I_READ_SNAPSHOTS}" = "no" ] ||\
+            [ "${CAN_I_CREATE_INTERNALREQUESTS}" = "no" ] ; then
+          echo "Error: Cannot read or create required Release resources!"
           echo ""
-          echo "CAN_I_READ_RELEASES? ${CAN_I_READ_RELEASES}"
-          echo "CAN_I_READ_RELEASEPLANS? ${CAN_I_READ_RELEASEPLANS}"
-          echo "CAN_I_READ_RELEASEPLANADMISSIONS? ${CAN_I_READ_RELEASEPLANADMISSIONS}"
-          echo "CAN_I_READ_RELEASESERVICECONFIG? ${CAN_I_READ_RELEASESERVICECONFIG}"
-          echo "CAN_I_READ_SNAPSHOTS? ${CAN_I_READ_SNAPSHOTS}"
-          echo ""
-          echo "CAN_I_CREATE_INTERNALREQUESTS? ${CAN_I_CREATE_INTERNALREQUESTS}"
-          echo ""
+          echo "This indicates that your workspace is not correctly setup"
+          echo "Please reach out to a workspace administrator"
+          exit 1
+        fi
 
-          if [ "${CAN_I_READ_RELEASES}" = "no" ] ||\
-              [ "${CAN_I_READ_RELEASEPLANS}" = "no" ] ||\
-              [ "${CAN_I_READ_RELEASEPLANADMISSIONS}" = "no" ] ||\
-              [ "${CAN_I_READ_RELEASESERVICECONFIG}" = "no" ] ||\
-              [ "${CAN_I_READ_SNAPSHOTS}" = "no" ] ||\
-              [ "${CAN_I_CREATE_INTERNALREQUESTS}" = "no" ] ; then
-            echo "Error: Cannot read or create required Release resources!"
-            echo ""
-            echo "This indicates that your workspace is not correctly setup"
-            echo "Please reach out to a workspace administrator"
-            exit 1
-          fi
-
-          echo "Access to Release resources verified"
+        echo "Access to Release resources verified"
